# Generated by Django 5.0.14 on 2026-06-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("comercial", "Comercial"),
                            ("terreno", "Terreno"),
                            ("rural", "Rural"),
                            ("sala", "Sala/Escritório"),
                            ("galpao", "Galpão"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("aluguel", "Aluguel"),
                            ("venda", "Venda"),
                            ("ambos", "Aluguel e Venda"),
                        ],
                        default="aluguel",
                        max_length=10,
                        verbose_name="Finalidade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("alugado", "Alugado"),
                            ("vendido", "Vendido"),
                            ("manutencao", "Em Manutenção"),
                            ("inativo", "Inativo"),
                        ],
                        default="disponivel",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(max_length=200, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "area_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Área Total (m²)",
                    ),
                ),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Área Construída (m²)",
                    ),
                ),
                (
                    "quartos",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Quartos"),
                ),
                (
                    "suites",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Suítes"),
                ),
                (
                    "banheiros",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Banheiros"
                    ),
                ),
                (
                    "vagas",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Vagas de Garagem"
                    ),
                ),
                (
                    "mobilia",
                    models.CharField(
                        choices=[
                            ("sem", "Sem Mobília"),
                            ("semi", "Semi-Mobiliado"),
                            ("mobiliado", "Mobiliado"),
                        ],
                        default="sem",
                        max_length=20,
                        verbose_name="Mobília",
                    ),
                ),
                ("piscina", models.BooleanField(default=False, verbose_name="Piscina")),
                (
                    "academia",
                    models.BooleanField(default=False, verbose_name="Academia"),
                ),
                (
                    "churrasqueira",
                    models.BooleanField(default=False, verbose_name="Churrasqueira"),
                ),
                (
                    "portaria",
                    models.BooleanField(default=False, verbose_name="Portaria 24h"),
                ),
                (
                    "elevador",
                    models.BooleanField(default=False, verbose_name="Elevador"),
                ),
                (
                    "pet_friendly",
                    models.BooleanField(default=False, verbose_name="Aceita Pet"),
                ),
                (
                    "valor_aluguel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Aluguel (R$)",
                    ),
                ),
                (
                    "valor_venda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor Venda (R$)",
                    ),
                ),
                (
                    "valor_condominio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Condomínio (R$)",
                    ),
                ),
                (
                    "valor_iptu",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="IPTU Mensal (R$)",
                    ),
                ),
                (
                    "proprietario_nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Proprietário"
                    ),
                ),
                (
                    "proprietario_cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "proprietario_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "proprietario_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição/Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imoveis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="FotoImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="imoveis/fotos/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Foto Principal"),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="imoveis.imovel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Imóvel",
                "verbose_name_plural": "Fotos do Imóvel",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
