# Generated by Django 5.0.14 on 2026-06-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="area_comum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Área Comum",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="area_privativa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Área Privativa",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="area_util",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Área Útil / de Piso",
            ),
        ),
    ]
