# Generated by Django 5.0.14 on 2026-07-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0002_imovel_area_comum_imovel_area_privativa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="nome_imovel",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome do Imóvel"
            ),
        ),
    ]
