# Generated by Django 5.0.14 on 2026-07-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0005_migrar_dados_proprietario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Edificio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Edifício"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("residencial", "Residencial"),
                            ("comercial", "Comercial"),
                            ("misto", "Misto"),
                        ],
                        default="residencial",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Logradouro"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=2, verbose_name="Estado"),
                ),
                (
                    "tipo_imovel_padrao",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("comercial", "Comercial"),
                            ("terreno", "Terreno"),
                            ("rural", "Rural"),
                            ("sala", "Sala/Escritório"),
                            ("galpao", "Galpão"),
                            ("outro", "Outro"),
                        ],
                        default="apartamento",
                        max_length=20,
                        verbose_name="Tipo padrão das unidades",
                    ),
                ),
                (
                    "finalidade_padrao",
                    models.CharField(
                        choices=[
                            ("aluguel", "Aluguel"),
                            ("venda", "Venda"),
                            ("ambos", "Aluguel e Venda"),
                        ],
                        default="aluguel",
                        max_length=20,
                        verbose_name="Finalidade padrão das unidades",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "proprietario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edificios",
                        to="imoveis.proprietario",
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edificios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edifício",
                "verbose_name_plural": "Edifícios",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="imovel",
            name="edificio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades",
                to="imoveis.edificio",
                verbose_name="Edifício",
            ),
        ),
    ]
