# Generated by Django 5.0.14 on 2026-07-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0006_add_edificio_model_e_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imovel",
            name="proprietario_cpf_cnpj",
        ),
        migrations.RemoveField(
            model_name="imovel",
            name="proprietario_email",
        ),
        migrations.RemoveField(
            model_name="imovel",
            name="proprietario_nome",
        ),
        migrations.RemoveField(
            model_name="imovel",
            name="proprietario_telefone",
        ),
    ]
