# Generated by Django 5.0.14 on 2026-07-29 11:44

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0007_remove_campos_texto_proprietario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoimovel",
            name="imagem",
            field=models.ImageField(
                upload_to=apps.core.storage.upload_to_imoveis_fotos,
                verbose_name="Imagem",
            ),
        ),
    ]
