# Generated by Django 5.0.14 on 2026-07-29 12:17

import apps.core.storage
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0008_alter_fotoimovel_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoimovel",
            name="imagem",
            field=models.ImageField(
                upload_to=apps.core.storage.upload_to_imoveis_fotos,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.core.validators.validate_file_size(5),
                ],
                verbose_name="Imagem",
            ),
        ),
    ]
