# Generated by Django 5.0.14 on 2026-06-08 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("contrato_criado", "Contrato criado"),
                            ("parcela_lembrete", "Lembrete de vencimento"),
                            ("parcela_vencida", "Cobrança de parcela vencida"),
                            ("pagamento_confirmado", "Pagamento confirmado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        help_text="Número no formato 5511999999999", max_length=20
                    ),
                ),
                ("nome_contato", models.CharField(blank=True, max_length=120)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("erro", "Erro"),
                            ("pendente", "Pendente"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("erro_detalhe", models.TextField(blank=True)),
                ("enviado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("contrato_id", models.IntegerField(blank=True, null=True)),
                ("parcela_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log de Mensagem",
                "verbose_name_plural": "Logs de Mensagens",
                "ordering": ["-enviado_em"],
            },
        ),
    ]
