# Generated by Django 5.0.14 on 2026-07-29 11:44

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_usuario_groups_alter_usuario_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_usuarios_fotos,
            ),
        ),
    ]
