# Generated by Django 5.0.14 on 2026-07-29 12:17

import apps.core.storage
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_migrate_existing_files_to_tenant_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_usuarios_fotos,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.core.validators.validate_file_size(2),
                ],
            ),
        ),
    ]
