# Generated by Django 5.0.14 on 2026-06-06 18:56

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("profissional", "Profissional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("preco_mensal", models.DecimalField(decimal_places=2, max_digits=8)),
                ("limite_imoveis", models.PositiveIntegerField(default=50)),
                ("limite_contratos", models.PositiveIntegerField(default=100)),
                ("limite_usuarios", models.PositiveIntegerField(default=5)),
                ("whatsapp_incluido", models.BooleanField(default=False)),
                ("relatorios_avancados", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plano",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=200)),
                ("razao_social", models.CharField(blank=True, max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=18)),
                ("email_contato", models.EmailField(max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tenants/logos/"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("trial_ate", models.DateField(blank=True, null=True)),
                ("plano_vence_em", models.DateField(blank=True, null=True)),
                ("cor_primaria", models.CharField(default="#1e40af", max_length=7)),
                ("cor_secundaria", models.CharField(default="#0f766e", max_length=7)),
                (
                    "plano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.plano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imobiliária",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domínio",
            },
        ),
    ]
