# Generated by Django 5.0.14 on 2026-06-07 01:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_fase2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigSicredi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=200)),
                ("client_secret", models.CharField(max_length=200)),
                (
                    "cooperativa",
                    models.CharField(
                        help_text="Código da cooperativa (4 dígitos)", max_length=4
                    ),
                ),
                (
                    "posto",
                    models.CharField(
                        help_text="Posto atendimento (2 dígitos)", max_length=2
                    ),
                ),
                ("conta", models.CharField(help_text="Número da conta", max_length=10)),
                (
                    "beneficiario",
                    models.CharField(
                        help_text="Nome do beneficiário no boleto", max_length=200
                    ),
                ),
                (
                    "ambiente",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("producao", "Produção")],
                        default="sandbox",
                        max_length=10,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True, help_text="Secret HMAC do webhook", max_length=100
                    ),
                ),
                ("ativo", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Config Sicredi",
                "verbose_name_plural": "Config Sicredi",
            },
        ),
        migrations.AlterModelOptions(
            name="domain",
            options={},
        ),
        migrations.AlterModelOptions(
            name="plano",
            options={"verbose_name": "Plano", "verbose_name_plural": "Planos"},
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "verbose_name": "Imobiliária",
                "verbose_name_plural": "Imobiliárias",
            },
        ),
        migrations.RenameField(
            model_name="plano",
            old_name="relatorios_avancados",
            new_name="tem_whatsapp",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="email_contato",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="nome_fantasia",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="plano",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="plano",
            name="whatsapp_incluido",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="plano_vence_em",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="razao_social",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="trial_ate",
        ),
        migrations.AddField(
            model_name="tenant",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="cep",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="tenant",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="endereco",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="instanciawhatsapp",
            name="nome_instancia",
            field=models.CharField(
                help_text="ID único na Evolution API", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="instanciawhatsapp",
            name="numero_telefone",
            field=models.CharField(
                blank=True, help_text="Número conectado", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="instanciawhatsapp",
            name="qr_code",
            field=models.TextField(blank=True, help_text="Base64 do QR Code atual"),
        ),
        migrations.AlterField(
            model_name="plano",
            name="limite_contratos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plano",
            name="limite_imoveis",
            field=models.IntegerField(
                blank=True, help_text="None = ilimitado", null=True
            ),
        ),
        migrations.AlterField(
            model_name="plano",
            name="limite_usuarios",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plano",
            name="nome",
            field=models.CharField(
                choices=[
                    ("basico", "Básico"),
                    ("profissional", "Profissional"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="templatewhatsapp",
            name="mensagem",
            field=models.TextField(help_text="Use {variavel} para campos dinâmicos"),
        ),
        migrations.AlterField(
            model_name="templatewhatsapp",
            name="variaveis_disponiveis",
            field=models.JSONField(
                default=list, help_text="Lista de variáveis permitidas"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="cor_primaria",
            field=models.CharField(
                default="#1a56db", help_text="Hex color", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plano",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenants.plano",
            ),
        ),
    ]
