# Generated by Django 5.0.14 on 2026-06-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_configsicredi_alter_domain_options_and_more"),
        ("tenants", "migration_evolution_url"),
    ]

    operations = []
