# Generated by Django 5.0.14 on 2026-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_merge_20260608_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="configsicredi",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="client_id do Portal do Desenvolvedor Sicredi (header x-api-key)",
                max_length=200,
                verbose_name="x-api-key",
            ),
        ),
        migrations.AddField(
            model_name="configsicredi",
            name="codigo_acesso",
            field=models.CharField(
                blank=True,
                help_text="Código de acesso gerado no Internet Banking (senha do token)",
                max_length=100,
                verbose_name="Código de acesso",
            ),
        ),
        migrations.AddField(
            model_name="configsicredi",
            name="codigo_beneficiario",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código numérico do beneficiário (ex: 12345). Usado pelo webhook.",
                max_length=20,
                verbose_name="Código do beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="configsicredi",
            name="schema_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Schema do tenant dono desta config (preenchido ao salvar no schema do tenant)",
                max_length=63,
                verbose_name="Schema do tenant",
            ),
        ),
        migrations.AlterField(
            model_name="configsicredi",
            name="client_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="configsicredi",
            name="client_secret",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="configsicredi",
            name="conta",
            field=models.CharField(
                blank=True, help_text="Número da conta", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="configsicredi",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret HMAC do webhook (opcional)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="instanciawhatsapp",
            name="evolution_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL base da Evolution API, ex: http://192.168.1.100:8080",
                verbose_name="URL da Evolution API",
            ),
        ),
        migrations.AddConstraint(
            model_name="configsicredi",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codigo_beneficiario", ""), _negated=True),
                fields=("codigo_beneficiario",),
                name="unique_codigo_beneficiario_sicredi",
            ),
        ),
    ]
