# Generated by Django 5.0.14 on 2026-06-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_configsicredi_api_key_configsicredi_codigo_acesso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="provisionamento_status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("provisionando", "Provisionando"),
                    ("pronto", "Pronto"),
                    ("erro", "Erro"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plano",
            name="preco_mensal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="cor_secundaria",
            field=models.CharField(default="#1e429f", max_length=7),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
