# Generated by Django 5.0.14 on 2026-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_provisionamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='tem_sicredi',
            field=models.BooleanField(default=False, help_text='Plano inclui integração Sicredi (exige CNPJ/PJ)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de pessoa'),
        ),
    ]
