# Generated by Django 5.0.14 on 2026-07-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_plano_tem_sicredi_tenant_cpf_tenant_tipo_pessoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="aceite_termos_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aceite dos termos em"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="aceite_termos_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP do aceite"
            ),
        ),
    ]
