# Generated by Django 5.0.14 on 2026-07-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_aceite_termos_em_tenant_aceite_termos_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="plano",
            name="destaque",
            field=models.BooleanField(
                default=False, help_text='Exibido como "Mais indicado" na landing page'
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="aceite_termos_user_agent",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="User-Agent do aceite",
            ),
        ),
    ]
