# Generated by Django 5.0.14 on 2026-07-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_fixar_planos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="asaas_customer_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Asaas customer ID"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="asaas_subscription_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Asaas subscription ID"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("ativo", "Ativo"),
                    ("inadimplente", "Inadimplente"),
                    ("suspenso", "Suspenso"),
                    ("cancelado", "Cancelado"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
