# Generated by Django 5.0.14 on 2026-07-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_tenant_asaas_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="asaas_graca_ate",
            field=models.DateField(
                blank=True,
                help_text="Data limite do período de graça após inadimplência. Quando setar: decisão pendente (TODO Fatia 2+).",
                null=True,
                verbose_name="Graça até",
            ),
        ),
    ]
