# Generated by Django 5.0.14 on 2026-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_tenant_asaas_graca_ate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instanciawhatsapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("desconectado", "Desconectado"),
                    ("aguardando_qr", "Aguardando QR Code"),
                    ("conectado", "Conectado"),
                    ("erro", "Erro"),
                    ("nao_encontrada", "Não encontrada no servidor"),
                ],
                default="desconectado",
                max_length=20,
            ),
        ),
    ]
