# Generated by Django 5.0.14 on 2026-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_alter_instanciawhatsapp_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="cobranca_liberada",
            field=models.BooleanField(
                default=False,
                help_text="Marca que o superadmin auditou o cadastro e liberou a cobrança recorrente no Asaas. Não significa pagamento confirmado.",
                verbose_name="Cobrança liberada",
            ),
        ),
    ]
