# Generated by Django 5.0.14 on 2026-07-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_tenant_cobranca_liberada"),
    ]

    operations = [
        migrations.AddField(
            model_name="instanciawhatsapp",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instancias_whatsapp",
                to="tenants.tenant",
                verbose_name="Imobiliária",
            ),
        ),
    ]
