# Generated by Django 5.0.14 on 2026-07-29 11:44

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_instanciawhatsapp_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_tenant_logos,
            ),
        ),
    ]
