# Generated by Django 5.0.14 on 2026-07-29 12:17

import apps.core.storage
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_alter_tenant_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_tenant_logos,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "svg", "webp"]
                    ),
                    apps.core.validators.validate_file_size(1),
                ],
            ),
        ),
    ]
