# Generated by Django 5.0.14 on 2026-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sicredi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="erro_mensagem",
            field=models.TextField(blank=True, verbose_name="Mensagem de erro"),
        ),
        migrations.AddField(
            model_name="boleto",
            name="pago_em",
            field=models.DateField(blank=True, null=True, verbose_name="Pago em"),
        ),
        migrations.AddField(
            model_name="boleto",
            name="qr_code",
            field=models.TextField(blank=True, verbose_name="QR Code (PIX)"),
        ),
        migrations.AddField(
            model_name="boleto",
            name="seu_numero",
            field=models.CharField(
                blank=True,
                help_text="Controle interno (ex: CT0001-P03)",
                max_length=30,
                verbose_name="Seu Número",
            ),
        ),
        migrations.AddField(
            model_name="boleto",
            name="txid",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="TXID (PIX)"
            ),
        ),
        migrations.AddField(
            model_name="boleto",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor Pago",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="status",
            field=models.CharField(
                choices=[
                    ("emitido", "Emitido"),
                    ("pago", "Pago"),
                    ("vencido", "Vencido"),
                    ("cancelado", "Cancelado"),
                    ("erro", "Erro"),
                ],
                default="emitido",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
