# Generated by Django 5.0.14 on 2026-07-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sicredi", "0002_boleto_erro_mensagem_boleto_pago_em_boleto_qr_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boleto",
            name="url_boleto",
        ),
    ]
