# Generated by Django 5.0.14 on 2026-07-15 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contratos", "0003_contrato_regra_competencia_parcela_competencia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloDocumento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato de Locação"),
                            ("distrato", "Distrato"),
                            ("recibo", "Recibo de Pagamento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "conteudo_html",
                    models.TextField(blank=True, default="", verbose_name="Conteúdo"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Modelos padrão não podem ser excluídos, apenas editados.",
                        verbose_name="Padrão do sistema",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modelo de Documento",
                "verbose_name_plural": "Modelos de Documento",
                "ordering": ["tipo", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="VariavelDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="Nome amigável"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("inquilino", "Inquilino"),
                            ("imovel", "Imóvel"),
                            ("contrato", "Contrato"),
                            ("proprietario", "Proprietário"),
                            ("fiador", "Fiador"),
                            ("data", "Data"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Variável de Documento",
                "verbose_name_plural": "Variáveis de Documento",
                "ordering": ["categoria", "label"],
            },
        ),
        migrations.CreateModel(
            name="ContratoDocumentoGerado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "conteudo_final_html",
                    models.TextField(verbose_name="Conteúdo renderizado"),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos/contratos/%Y/%m/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("gerado", "Gerado"), ("erro", "Erro na geração")],
                        default="gerado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("gerado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_gerados",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "gerado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_gerados",
                        to="documentos.modelodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Gerado",
                "verbose_name_plural": "Documentos Gerados",
                "ordering": ["-gerado_em"],
            },
        ),
        migrations.CreateModel(
            name="ModeloDocumentoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo_html", models.TextField()),
                ("salvo_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="documentos.modelodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Modelo",
                "verbose_name_plural": "Histórico de Modelos",
                "ordering": ["-salvo_em"],
            },
        ),
    ]
