# Generated by Django 5.0.14 on 2026-07-29 11:44

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratodocumentogerado",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_documentos_contratos,
                verbose_name="PDF",
            ),
        ),
    ]
