# Generated by Django 5.0.14 on 2026-10-02 13:21

import apps.core.storage
import apps.documentos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0002_alter_contratodocumentogerado_arquivo_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelodocumento",
            name="arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_documentos_modelos,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx"], message="Envie um arquivo .docx."
                    ),
                    apps.documentos.validators.validar_tamanho_modelo,
                    apps.documentos.validators.ValidarDocx(),
                ],
                verbose_name="Arquivo .docx",
            ),
        ),
    ]
