# Generated by Django 5.0.14 on 2026-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_modelodocumento_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratodocumentogerado",
            name="erro_msg",
            field=models.TextField(
                blank=True, default="", verbose_name="Mensagem de erro"
            ),
        ),
        migrations.AlterField(
            model_name="contratodocumentogerado",
            name="conteudo_final_html",
            field=models.TextField(
                blank=True, default="", verbose_name="Conteúdo renderizado"
            ),
        ),
        migrations.AlterField(
            model_name="contratodocumentogerado",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("processando", "Processando"),
                    ("gerado", "Gerado"),
                    ("erro", "Erro na geração"),
                ],
                default="gerado",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
