# Generated by Django 5.0.14 on 2026-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_contratodocumentogerado_erro_msg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelodocumento",
            name="predefinido",
            field=models.BooleanField(
                default=False,
                help_text="Modelo pré-selecionado na geração de documentos do tipo. Um por tipo.",
                verbose_name="Padrão da imobiliária",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelodocumento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True), ("predefinido", True)),
                fields=("tipo",),
                name="documentos_modelo_um_predefinido_ativo_por_tipo",
            ),
        ),
    ]
