# Generated by Django 5.0.14 on 2026-06-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquilino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pf", "Pessoa Física"), ("pj", "Pessoa Jurídica")],
                        default="pf",
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("inadimplente", "Inadimplente"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome Completo / Razão Social"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, max_length=20, verbose_name="RG")),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("uniao", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "profissao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão"
                    ),
                ),
                (
                    "renda_mensal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Renda Mensal (R$)",
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        blank=True,
                        default="Brasileira",
                        max_length=50,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "razao_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razão Social"
                    ),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Inscrição Estadual"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(max_length=20, verbose_name="Telefone / WhatsApp"),
                ),
                (
                    "telefone2",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone 2"
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=2, verbose_name="Estado"),
                ),
                (
                    "fiador_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Fiador"
                    ),
                ),
                (
                    "fiador_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do Fiador"
                    ),
                ),
                (
                    "fiador_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone do Fiador"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inquilinos/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inquilino",
                "verbose_name_plural": "Inquilinos",
                "ordering": ["nome"],
            },
        ),
    ]
