# Generated by Django 5.0.14 on 2026-07-29 11:44

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquilinos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquilino",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.upload_to_inquilinos_fotos,
                verbose_name="Foto",
            ),
        ),
    ]
