# Generated by Django 5.0.14 on 2026-06-17 22:51

import django.contrib.admin.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logentry',
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time'),
        ),
    ]
