# Generated by Django 5.0.14 on 2026-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="percentual_fixo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Usado apenas quando índice = Percentual Fixo",
                max_digits=5,
                verbose_name="Percentual Fixo (%)",
            ),
        ),
    ]
