# Generated by Django 5.0.14 on 2026-07-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0002_alter_contrato_percentual_fixo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="regra_competencia",
            field=models.CharField(
                choices=[
                    ("mesmo_mes", "Mesmo mês do vencimento"),
                    ("mes_anterior", "Mês anterior ao vencimento"),
                ],
                default="mesmo_mes",
                max_length=15,
                verbose_name="Regra de Competência",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="competencia",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="Competência"
            ),
        ),
    ]
